// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertNarInfoReferences implements pgx.CopyFromSource.
type iteratorForInsertNarInfoReferences struct {
	rows                 []InsertNarInfoReferencesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertNarInfoReferences) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertNarInfoReferences) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Hash,
		r.rows[0].RefersTo,
	}, nil
}

func (r iteratorForInsertNarInfoReferences) Err() error {
	return nil
}

func (q *Queries) InsertNarInfoReferences(ctx context.Context, arg []InsertNarInfoReferencesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"nar_info_reference"}, []string{"hash", "refers_to"}, &iteratorForInsertNarInfoReferences{rows: arg})
}

// iteratorForInsertNarInfoSignatures implements pgx.CopyFromSource.
type iteratorForInsertNarInfoSignatures struct {
	rows                 []InsertNarInfoSignaturesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertNarInfoSignatures) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertNarInfoSignatures) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Hash,
		r.rows[0].Name,
		r.rows[0].Data,
	}, nil
}

func (r iteratorForInsertNarInfoSignatures) Err() error {
	return nil
}

func (q *Queries) InsertNarInfoSignatures(ctx context.Context, arg []InsertNarInfoSignaturesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"nar_info_signature"}, []string{"hash", "name", "data"}, &iteratorForInsertNarInfoSignatures{rows: arg})
}
