// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompressionType string

const (
	CompressionTypeXz    CompressionType = "xz"
	CompressionTypeBzip2 CompressionType = "bzip2"
	CompressionTypeGzip  CompressionType = "gzip"
	CompressionTypeZstd  CompressionType = "zstd"
	CompressionTypeNone  CompressionType = "none"
)

func (e *CompressionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompressionType(s)
	case string:
		*e = CompressionType(s)
	default:
		return fmt.Errorf("unsupported scan type for CompressionType: %T", src)
	}
	return nil
}

type NullCompressionType struct {
	CompressionType CompressionType `json:"compression_type"`
	Valid           bool            `json:"valid"` // Valid is true if CompressionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompressionType) Scan(value interface{}) error {
	if value == nil {
		ns.CompressionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompressionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompressionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompressionType), nil
}

type NarFile struct {
	Hash           string           `json:"hash"`
	Compression    CompressionType  `json:"compression"`
	Bucket         string           `json:"bucket"`
	Path           string           `json:"path"`
	Size           int64            `json:"size"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastAccessedAt pgtype.Timestamp `json:"last_accessed_at"`
}

type NarInfo struct {
	Hash           string           `json:"hash"`
	StorePath      string           `json:"store_path"`
	Compression    CompressionType  `json:"compression"`
	FileHash       string           `json:"file_hash"`
	FileSize       int64            `json:"file_size"`
	NarHash        string           `json:"nar_hash"`
	NarSize        int64            `json:"nar_size"`
	Deriver        string           `json:"deriver"`
	Bucket         string           `json:"bucket"`
	Path           string           `json:"path"`
	Size           int32            `json:"size"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastAccessedAt pgtype.Timestamp `json:"last_accessed_at"`
}

type NarInfoReference struct {
	Hash     string `json:"hash"`
	RefersTo string `json:"refers_to"`
}

type NarInfoSignature struct {
	Hash      string `json:"hash"`
	Signature string `json:"signature"`
}
