// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompressionType string

const (
	CompressionTypeBr       CompressionType = "br"
	CompressionTypeCompress CompressionType = "compress"
	CompressionTypeGrzip    CompressionType = "grzip"
	CompressionTypeGzip     CompressionType = "gzip"
	CompressionTypeLrzip    CompressionType = "lrzip"
	CompressionTypeLz4      CompressionType = "lz4"
	CompressionTypeLzip     CompressionType = "lzip"
	CompressionTypeLzma     CompressionType = "lzma"
	CompressionTypeLzop     CompressionType = "lzop"
	CompressionTypeXz       CompressionType = "xz"
	CompressionTypeZstd     CompressionType = "zstd"
	CompressionTypeNone     CompressionType = "none"
)

func (e *CompressionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompressionType(s)
	case string:
		*e = CompressionType(s)
	default:
		return fmt.Errorf("unsupported scan type for CompressionType: %T", src)
	}
	return nil
}

type NullCompressionType struct {
	CompressionType CompressionType `json:"compression_type"`
	Valid           bool            `json:"valid"` // Valid is true if CompressionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompressionType) Scan(value interface{}) error {
	if value == nil {
		ns.CompressionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompressionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompressionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompressionType), nil
}

type ObjectType string

const (
	ObjectTypeNar     ObjectType = "nar"
	ObjectTypeNarinfo ObjectType = "narinfo"
	ObjectTypeLs      ObjectType = "ls"
	ObjectTypeLog     ObjectType = "log"
	ObjectTypeDebug   ObjectType = "debug"
)

func (e *ObjectType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ObjectType(s)
	case string:
		*e = ObjectType(s)
	default:
		return fmt.Errorf("unsupported scan type for ObjectType: %T", src)
	}
	return nil
}

type NullObjectType struct {
	ObjectType ObjectType `json:"object_type"`
	Valid      bool       `json:"valid"` // Valid is true if ObjectType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullObjectType) Scan(value interface{}) error {
	if value == nil {
		ns.ObjectType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ObjectType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullObjectType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ObjectType), nil
}

type GcPlan struct {
	ID          int32            `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	AppliedAt   pgtype.Timestamp `json:"applied_at"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
	Error       pgtype.Text      `json:"error"`
}

type GcRoot struct {
	Hash      string           `json:"hash"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type NarInfo struct {
	Hash        string          `json:"hash"`
	Url         string          `json:"url"`
	StorePath   string          `json:"store_path"`
	Compression CompressionType `json:"compression"`
	FileHash    string          `json:"file_hash"`
	FileSize    int64           `json:"file_size"`
	NarHash     string          `json:"nar_hash"`
	NarSize     int64           `json:"nar_size"`
	Deriver     string          `json:"deriver"`
}

type NarInfoReference struct {
	Hash     string `json:"hash"`
	RefersTo string `json:"refers_to"`
}

type NarInfoSignature struct {
	Hash string `json:"hash"`
	Name string `json:"name"`
	Data string `json:"data"`
}

type Object struct {
	Hash            string           `json:"hash"`
	ObjectType      ObjectType       `json:"object_type"`
	CompressionType CompressionType  `json:"compression_type"`
	Path            string           `json:"path"`
	Size            int64            `json:"size"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	LastAccessedAt  pgtype.Timestamp `json:"last_accessed_at"`
}
