// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
)

const checkObjectsExistByTypeHashSize = `-- name: CheckObjectsExistByTypeHashSize :many
select o.hash, o.object_type, o.size, o.path
from object o
inner join (
    select
        unnest($1::text[])::object_type as object_type,
        unnest($2::varchar[]) as hash,
        unnest($3::bigint[]) as size
) input on o.object_type = input.object_type
    and o.hash = input.hash
    and o.size = input.size
`

type CheckObjectsExistByTypeHashSizeParams struct {
	Column1 []string `json:"column_1"`
	Column2 []string `json:"column_2"`
	Column3 []int64  `json:"column_3"`
}

type CheckObjectsExistByTypeHashSizeRow struct {
	Hash       string     `json:"hash"`
	ObjectType ObjectType `json:"object_type"`
	Size       int64      `json:"size"`
	Path       string     `json:"path"`
}

// Check which objects already exist in the database by (object_type, hash, size)
// This query takes three parallel arrays and returns matching objects
func (q *Queries) CheckObjectsExistByTypeHashSize(ctx context.Context, arg CheckObjectsExistByTypeHashSizeParams) ([]CheckObjectsExistByTypeHashSizeRow, error) {
	rows, err := q.db.Query(ctx, checkObjectsExistByTypeHashSize, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckObjectsExistByTypeHashSizeRow
	for rows.Next() {
		var i CheckObjectsExistByTypeHashSizeRow
		if err := rows.Scan(
			&i.Hash,
			&i.ObjectType,
			&i.Size,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteGCPlan = `-- name: DeleteGCPlan :one
with deleted as (
    delete from gc_plan where id = $1 returning id, created_at, completed_at
) select count(*) from deleted
`

func (q *Queries) DeleteGCPlan(ctx context.Context, id int32) (int64, error) {
	row := q.db.QueryRow(ctx, deleteGCPlan, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGCRoot = `-- name: DeleteGCRoot :one
with deleted as (
    delete from gc_root where hash = $1 returning hash, created_at
) select count(*) from deleted
`

func (q *Queries) DeleteGCRoot(ctx context.Context, hash string) (int64, error) {
	row := q.db.QueryRow(ctx, deleteGCRoot, hash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNarInfoReferences = `-- name: DeleteNarInfoReferences :exec
delete from nar_info_reference
where hash = $1
`

func (q *Queries) DeleteNarInfoReferences(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteNarInfoReferences, hash)
	return err
}

const deleteNarInfoSignatures = `-- name: DeleteNarInfoSignatures :exec
delete from nar_info_signature
where hash = $1
`

func (q *Queries) DeleteNarInfoSignatures(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteNarInfoSignatures, hash)
	return err
}

const getGCPlan = `-- name: GetGCPlan :one
select id, created_at, completed_at from gc_plan where id = $1
`

func (q *Queries) GetGCPlan(ctx context.Context, id int32) (GcPlan, error) {
	row := q.db.QueryRow(ctx, getGCPlan, id)
	var i GcPlan
	err := row.Scan(&i.ID, &i.CreatedAt, &i.CompletedAt)
	return i, err
}

const getObjectByHash = `-- name: GetObjectByHash :one
select object_type, compression_type, size
from object as o
where o.hash = $1
`

type GetObjectByHashRow struct {
	ObjectType      ObjectType      `json:"object_type"`
	CompressionType CompressionType `json:"compression_type"`
	Size            int64           `json:"size"`
}

func (q *Queries) GetObjectByHash(ctx context.Context, hash string) (GetObjectByHashRow, error) {
	row := q.db.QueryRow(ctx, getObjectByHash, hash)
	var i GetObjectByHashRow
	err := row.Scan(&i.ObjectType, &i.CompressionType, &i.Size)
	return i, err
}

const hasObject = `-- name: HasObject :one
with update_accessed as (
    update object
    set last_accessed_at = timezone('UTC', now())
    where path = $1
)
select object_type, compression_type, size
from object as o
where o.path = $1
`

type HasObjectRow struct {
	ObjectType      ObjectType      `json:"object_type"`
	CompressionType CompressionType `json:"compression_type"`
	Size            int64           `json:"size"`
}

func (q *Queries) HasObject(ctx context.Context, path string) (HasObjectRow, error) {
	row := q.db.QueryRow(ctx, hasObject, path)
	var i HasObjectRow
	err := row.Scan(&i.ObjectType, &i.CompressionType, &i.Size)
	return i, err
}

const insertGCPlan = `-- name: InsertGCPlan :one
insert into gc_plan (created_at)
values (timezone('UTC', now()))
returning id
`

func (q *Queries) InsertGCPlan(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, insertGCPlan)
	var id int32
	err := row.Scan(&id)
	return id, err
}

type InsertNarInfoReferencesParams struct {
	Hash     string `json:"hash"`
	RefersTo string `json:"refers_to"`
}

type InsertNarInfoSignaturesParams struct {
	Hash string `json:"hash"`
	Name string `json:"name"`
	Data string `json:"data"`
}

const isManifestFileImported = `-- name: IsManifestFileImported :one
select exists(select 1 from imported_manifest_file where basename = $1)
`

func (q *Queries) IsManifestFileImported(ctx context.Context, basename string) (bool, error) {
	row := q.db.QueryRow(ctx, isManifestFileImported, basename)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGCPlans = `-- name: ListGCPlans :many
select id, created_at, completed_at from gc_plan
`

func (q *Queries) ListGCPlans(ctx context.Context) ([]GcPlan, error) {
	rows, err := q.db.Query(ctx, listGCPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GcPlan
	for rows.Next() {
		var i GcPlan
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGCRoots = `-- name: ListGCRoots :many
select hash from gc_root
`

func (q *Queries) ListGCRoots(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listGCRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var hash string
		if err := rows.Scan(&hash); err != nil {
			return nil, err
		}
		items = append(items, hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedManifestFiles = `-- name: ListImportedManifestFiles :many
select basename from imported_manifest_file where basename = ANY($1::varchar[])
`

func (q *Queries) ListImportedManifestFiles(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listImportedManifestFiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var basename string
		if err := rows.Scan(&basename); err != nil {
			return nil, err
		}
		items = append(items, basename)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedPaths = `-- name: ListImportedPaths :many
select path from object where path = ANY($1::varchar[])
`

func (q *Queries) ListImportedPaths(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listImportedPaths, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markManifestFileAsImported = `-- name: MarkManifestFileAsImported :exec
insert into imported_manifest_file (basename, md5_checksum, size, imported_at)
values ($1, $2, $3, timezone('UTC', now()))
on conflict (basename) do nothing
`

type MarkManifestFileAsImportedParams struct {
	Basename    string `json:"basename"`
	Md5Checksum string `json:"md5_checksum"`
	Size        int64  `json:"size"`
}

func (q *Queries) MarkManifestFileAsImported(ctx context.Context, arg MarkManifestFileAsImportedParams) error {
	_, err := q.db.Exec(ctx, markManifestFileAsImported, arg.Basename, arg.Md5Checksum, arg.Size)
	return err
}

const putGCRoot = `-- name: PutGCRoot :exec
insert into gc_root (hash, created_at)
values ($1, timezone('UTC', now()))
on conflict(hash) do nothing
`

func (q *Queries) PutGCRoot(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, putGCRoot, hash)
	return err
}

const putNarInfo = `-- name: PutNarInfo :exec
insert
into nar_info (hash, url, store_path, compression, file_hash, file_size, nar_hash, nar_size, deriver)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (hash) do update
    set url = excluded.url,
        store_path  = excluded.store_path ,
        compression = excluded.compression,
        file_hash   = excluded.file_hash,
        file_size   = excluded.file_size,
        nar_hash    = excluded.nar_hash,
        nar_size    = excluded.nar_size,
        deriver     = excluded.deriver
`

type PutNarInfoParams struct {
	Hash        string          `json:"hash"`
	Url         string          `json:"url"`
	StorePath   string          `json:"store_path"`
	Compression CompressionType `json:"compression"`
	FileHash    string          `json:"file_hash"`
	FileSize    int64           `json:"file_size"`
	NarHash     string          `json:"nar_hash"`
	NarSize     int64           `json:"nar_size"`
	Deriver     string          `json:"deriver"`
}

func (q *Queries) PutNarInfo(ctx context.Context, arg PutNarInfoParams) error {
	_, err := q.db.Exec(ctx, putNarInfo,
		arg.Hash,
		arg.Url,
		arg.StorePath,
		arg.Compression,
		arg.FileHash,
		arg.FileSize,
		arg.NarHash,
		arg.NarSize,
		arg.Deriver,
	)
	return err
}

const putObject = `-- name: PutObject :exec
insert into object (hash, object_type, compression_type, path, size, created_at)
values ($1, $2, $3, $4, $5, timezone('UTC', now()))
`

type PutObjectParams struct {
	Hash            string          `json:"hash"`
	ObjectType      ObjectType      `json:"object_type"`
	CompressionType CompressionType `json:"compression_type"`
	Path            string          `json:"path"`
	Size            int64           `json:"size"`
}

func (q *Queries) PutObject(ctx context.Context, arg PutObjectParams) error {
	_, err := q.db.Exec(ctx, putObject,
		arg.Hash,
		arg.ObjectType,
		arg.CompressionType,
		arg.Path,
		arg.Size,
	)
	return err
}

const setGCPlanAsCompleted = `-- name: SetGCPlanAsCompleted :exec
update gc_plan set completed_at = timezone('UTC', now()) where id = $1 and completed_at is null
`

func (q *Queries) SetGCPlanAsCompleted(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setGCPlanAsCompleted, id)
	return err
}
