// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
)

const deleteNarInfoReferences = `-- name: DeleteNarInfoReferences :exec
delete from nar_info_reference
where hash = $1
`

func (q *Queries) DeleteNarInfoReferences(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteNarInfoReferences, hash)
	return err
}

const deleteNarInfoSignatures = `-- name: DeleteNarInfoSignatures :exec
delete from nar_info_signature
where hash = $1
`

func (q *Queries) DeleteNarInfoSignatures(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteNarInfoSignatures, hash)
	return err
}

const hasNar = `-- name: HasNar :one
with update_accessed as (
    update nar_file
    set last_accessed_at = timezone('UTC', now())
)
select bucket, path, size
from nar_file as nf
where nf.hash = $1
  and nf.compression = $2
`

type HasNarParams struct {
	Hash        string          `json:"hash"`
	Compression CompressionType `json:"compression"`
}

type HasNarRow struct {
	Bucket string `json:"bucket"`
	Path   string `json:"path"`
	Size   int64  `json:"size"`
}

func (q *Queries) HasNar(ctx context.Context, arg HasNarParams) (HasNarRow, error) {
	row := q.db.QueryRow(ctx, hasNar, arg.Hash, arg.Compression)
	var i HasNarRow
	err := row.Scan(&i.Bucket, &i.Path, &i.Size)
	return i, err
}

const hasNarInfo = `-- name: HasNarInfo :one
with update_accessed as (
    update nar_info
        set last_accessed_at = timezone('UTC', now())
)
select bucket,
       path,
       size
from nar_info as nf
where nf.hash = $1
`

type HasNarInfoRow struct {
	Bucket string `json:"bucket"`
	Path   string `json:"path"`
	Size   int32  `json:"size"`
}

func (q *Queries) HasNarInfo(ctx context.Context, hash string) (HasNarInfoRow, error) {
	row := q.db.QueryRow(ctx, hasNarInfo, hash)
	var i HasNarInfoRow
	err := row.Scan(&i.Bucket, &i.Path, &i.Size)
	return i, err
}

type InsertNarInfoReferencesParams struct {
	Hash     string `json:"hash"`
	RefersTo string `json:"refers_to"`
}

type InsertNarInfoSignaturesParams struct {
	Hash      string `json:"hash"`
	Signature string `json:"signature"`
}

const putNar = `-- name: PutNar :exec
insert into nar_file (hash, compression, bucket, path, size, created_at)
values ($1, $2, $3, $4, $5, timezone('UTC', now()))
on conflict(hash, compression) do update
    set bucket     = excluded.bucket,
        path       = excluded.path,
        size       = excluded.size,
        created_at = timezone('UTC', now())
`

type PutNarParams struct {
	Hash        string          `json:"hash"`
	Compression CompressionType `json:"compression"`
	Bucket      string          `json:"bucket"`
	Path        string          `json:"path"`
	Size        int64           `json:"size"`
}

func (q *Queries) PutNar(ctx context.Context, arg PutNarParams) error {
	_, err := q.db.Exec(ctx, putNar,
		arg.Hash,
		arg.Compression,
		arg.Bucket,
		arg.Path,
		arg.Size,
	)
	return err
}

const putNarInfo = `-- name: PutNarInfo :exec
insert
into nar_info (hash, store_path, compression, file_hash, file_size, nar_hash, nar_size, deriver, bucket, path, size,
               created_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, timezone('UTC', now()))
on conflict (hash) do update
    set store_path  = excluded.store_path,
        compression = excluded.compression,
        file_hash   = excluded.file_hash,
        file_size   = excluded.file_size,
        nar_hash    = excluded.nar_hash,
        nar_size    = excluded.nar_size,
        deriver     = excluded.deriver,
        bucket      = excluded.bucket,
        path        = excluded.path,
        size        = excluded.size,
        created_at  = timezone('UTC', now())
`

type PutNarInfoParams struct {
	Hash        string          `json:"hash"`
	StorePath   string          `json:"store_path"`
	Compression CompressionType `json:"compression"`
	FileHash    string          `json:"file_hash"`
	FileSize    int64           `json:"file_size"`
	NarHash     string          `json:"nar_hash"`
	NarSize     int64           `json:"nar_size"`
	Deriver     string          `json:"deriver"`
	Bucket      string          `json:"bucket"`
	Path        string          `json:"path"`
	Size        int32           `json:"size"`
}

func (q *Queries) PutNarInfo(ctx context.Context, arg PutNarInfoParams) error {
	_, err := q.db.Exec(ctx, putNarInfo,
		arg.Hash,
		arg.StorePath,
		arg.Compression,
		arg.FileHash,
		arg.FileSize,
		arg.NarHash,
		arg.NarSize,
		arg.Deriver,
		arg.Bucket,
		arg.Path,
		arg.Size,
	)
	return err
}
