// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
)

const deleteNarInfoReferences = `-- name: DeleteNarInfoReferences :exec
delete from nar_info_reference
where hash = $1
`

func (q *Queries) DeleteNarInfoReferences(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteNarInfoReferences, hash)
	return err
}

const deleteNarInfoSignatures = `-- name: DeleteNarInfoSignatures :exec
delete from nar_info_signature
where hash = $1
`

func (q *Queries) DeleteNarInfoSignatures(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteNarInfoSignatures, hash)
	return err
}

const hasObject = `-- name: HasObject :one
with update_accessed as (
    update object
    set last_accessed_at = timezone('UTC', now())
    where path = $1
)
select object_type, compression_type, bucket, size
from object as o
where o.path = $1
`

type HasObjectRow struct {
	ObjectType      ObjectType      `json:"object_type"`
	CompressionType CompressionType `json:"compression_type"`
	Bucket          string          `json:"bucket"`
	Size            int64           `json:"size"`
}

func (q *Queries) HasObject(ctx context.Context, path string) (HasObjectRow, error) {
	row := q.db.QueryRow(ctx, hasObject, path)
	var i HasObjectRow
	err := row.Scan(
		&i.ObjectType,
		&i.CompressionType,
		&i.Bucket,
		&i.Size,
	)
	return i, err
}

type InsertNarInfoReferencesParams struct {
	Hash     string `json:"hash"`
	RefersTo string `json:"refers_to"`
}

type InsertNarInfoSignaturesParams struct {
	Hash string `json:"hash"`
	Name string `json:"name"`
	Data string `json:"data"`
}

const putNarInfo = `-- name: PutNarInfo :exec
insert
into nar_info (hash, store_path, compression, file_hash, file_size, nar_hash, nar_size, deriver)
values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (hash) do update
    set store_path  = excluded.store_path ,
        compression = excluded.compression,
        file_hash   = excluded.file_hash,
        file_size   = excluded.file_size,
        nar_hash    = excluded.nar_hash,
        nar_size    = excluded.nar_size,
        deriver     = excluded.deriver
`

type PutNarInfoParams struct {
	Hash        string          `json:"hash"`
	StorePath   string          `json:"store_path"`
	Compression CompressionType `json:"compression"`
	FileHash    string          `json:"file_hash"`
	FileSize    int64           `json:"file_size"`
	NarHash     string          `json:"nar_hash"`
	NarSize     int64           `json:"nar_size"`
	Deriver     string          `json:"deriver"`
}

func (q *Queries) PutNarInfo(ctx context.Context, arg PutNarInfoParams) error {
	_, err := q.db.Exec(ctx, putNarInfo,
		arg.Hash,
		arg.StorePath,
		arg.Compression,
		arg.FileHash,
		arg.FileSize,
		arg.NarHash,
		arg.NarSize,
		arg.Deriver,
	)
	return err
}

const putObject = `-- name: PutObject :exec
insert into object (hash, object_type, compression_type, bucket, path, size, created_at)
values ($1, $2, $3, $4, $5, $6, timezone('UTC', now()))
on conflict(path) do update
    set bucket     = excluded.bucket,
        size       = excluded.size,
        created_at = timezone('UTC', now())
`

type PutObjectParams struct {
	Hash            string          `json:"hash"`
	ObjectType      ObjectType      `json:"object_type"`
	CompressionType CompressionType `json:"compression_type"`
	Bucket          string          `json:"bucket"`
	Path            string          `json:"path"`
	Size            int64           `json:"size"`
}

func (q *Queries) PutObject(ctx context.Context, arg PutObjectParams) error {
	_, err := q.db.Exec(ctx, putObject,
		arg.Hash,
		arg.ObjectType,
		arg.CompressionType,
		arg.Bucket,
		arg.Path,
		arg.Size,
	)
	return err
}
