version: "0.5"

processes:
    minio:
        command: |
            mkdir -p $MINIO_DATA/binary-cache            
            minio server $MINIO_DATA

    postgres:
        command: |
            postgres-init
            cd $PGDATA
            postgres
