// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForCopyBuildStepOutputs implements pgx.CopyFromSource.
type iteratorForCopyBuildStepOutputs struct {
	rows                 []CopyBuildStepOutputsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyBuildStepOutputs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyBuildStepOutputs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Build,
		r.rows[0].Stepnr,
		r.rows[0].Name,
		r.rows[0].Path,
	}, nil
}

func (r iteratorForCopyBuildStepOutputs) Err() error {
	return nil
}

func (q *Queries) CopyBuildStepOutputs(ctx context.Context, arg []CopyBuildStepOutputsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"buildstepoutputs"}, []string{"build", "stepnr", "name", "path"}, &iteratorForCopyBuildStepOutputs{rows: arg})
}

// iteratorForCopyBuildSteps implements pgx.CopyFromSource.
type iteratorForCopyBuildSteps struct {
	rows                 []CopyBuildStepsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyBuildSteps) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyBuildSteps) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Build,
		r.rows[0].Stepnr,
		r.rows[0].Type,
		r.rows[0].Drvpath,
		r.rows[0].Status,
		r.rows[0].Machine,
		r.rows[0].Starttime,
		r.rows[0].Stoptime,
		r.rows[0].Busy,
	}, nil
}

func (r iteratorForCopyBuildSteps) Err() error {
	return nil
}

func (q *Queries) CopyBuildSteps(ctx context.Context, arg []CopyBuildStepsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"buildsteps"}, []string{"build", "stepnr", "type", "drvpath", "status", "machine", "starttime", "stoptime", "busy"}, &iteratorForCopyBuildSteps{rows: arg})
}

// iteratorForCopyBuilds implements pgx.CopyFromSource.
type iteratorForCopyBuilds struct {
	rows                 []CopyBuildsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyBuilds) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyBuilds) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].JobsetID,
		r.rows[0].Job,
		r.rows[0].Drvpath,
		r.rows[0].System,
		r.rows[0].Finished,
		r.rows[0].Timestamp,
		r.rows[0].Buildstatus,
		r.rows[0].Priority,
		r.rows[0].Starttime,
		r.rows[0].Stoptime,
	}, nil
}

func (r iteratorForCopyBuilds) Err() error {
	return nil
}

// Bulk insert queries using COPY protocol
func (q *Queries) CopyBuilds(ctx context.Context, arg []CopyBuildsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"builds"}, []string{"jobset_id", "job", "drvpath", "system", "finished", "timestamp", "buildstatus", "priority", "starttime", "stoptime"}, &iteratorForCopyBuilds{rows: arg})
}
