// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CopyBuildStepOutputsParams struct {
	Build  int32       `json:"build"`
	Stepnr int32       `json:"stepnr"`
	Name   string      `json:"name"`
	Path   pgtype.Text `json:"path"`
}

type CopyBuildStepsParams struct {
	Build     int32       `json:"build"`
	Stepnr    int32       `json:"stepnr"`
	Type      int32       `json:"type"`
	Drvpath   pgtype.Text `json:"drvpath"`
	Status    pgtype.Int4 `json:"status"`
	Machine   string      `json:"machine"`
	Starttime pgtype.Int4 `json:"starttime"`
	Stoptime  pgtype.Int4 `json:"stoptime"`
	Busy      int32       `json:"busy"`
}

type CopyBuildsParams struct {
	JobsetID    int32       `json:"jobset_id"`
	Job         string      `json:"job"`
	Drvpath     string      `json:"drvpath"`
	System      string      `json:"system"`
	Finished    int32       `json:"finished"`
	Timestamp   int32       `json:"timestamp"`
	Buildstatus pgtype.Int4 `json:"buildstatus"`
	Priority    int32       `json:"priority"`
	Starttime   pgtype.Int4 `json:"starttime"`
	Stoptime    pgtype.Int4 `json:"stoptime"`
}

const countBuildStepOutputs = `-- name: CountBuildStepOutputs :one
SELECT COUNT(*) FROM buildstepoutputs
`

func (q *Queries) CountBuildStepOutputs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBuildStepOutputs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (jobset_id, job, drvpath, system, finished, timestamp, buildstatus, priority, starttime, stoptime)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, finished, timestamp, jobset_id, job, nixname, description, drvpath, system, license, homepage, maintainers, maxsilent, timeout, ischannel, iscurrent, priority, globalpriority, starttime, stoptime, iscachedbuild, buildstatus, size, closuresize, releasename, keep, notificationpendingsince
`

type CreateBuildParams struct {
	JobsetID    int32       `json:"jobset_id"`
	Job         string      `json:"job"`
	Drvpath     string      `json:"drvpath"`
	System      string      `json:"system"`
	Finished    int32       `json:"finished"`
	Timestamp   int32       `json:"timestamp"`
	Buildstatus pgtype.Int4 `json:"buildstatus"`
	Priority    int32       `json:"priority"`
	Starttime   pgtype.Int4 `json:"starttime"`
	Stoptime    pgtype.Int4 `json:"stoptime"`
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.JobsetID,
		arg.Job,
		arg.Drvpath,
		arg.System,
		arg.Finished,
		arg.Timestamp,
		arg.Buildstatus,
		arg.Priority,
		arg.Starttime,
		arg.Stoptime,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.Finished,
		&i.Timestamp,
		&i.JobsetID,
		&i.Job,
		&i.Nixname,
		&i.Description,
		&i.Drvpath,
		&i.System,
		&i.License,
		&i.Homepage,
		&i.Maintainers,
		&i.Maxsilent,
		&i.Timeout,
		&i.Ischannel,
		&i.Iscurrent,
		&i.Priority,
		&i.Globalpriority,
		&i.Starttime,
		&i.Stoptime,
		&i.Iscachedbuild,
		&i.Buildstatus,
		&i.Size,
		&i.Closuresize,
		&i.Releasename,
		&i.Keep,
		&i.Notificationpendingsince,
	)
	return i, err
}

const createBuildStep = `-- name: CreateBuildStep :exec
INSERT INTO buildsteps (build, stepnr, type, drvpath, status, machine, starttime, stoptime, busy)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 0)
`

type CreateBuildStepParams struct {
	Build     int32       `json:"build"`
	Stepnr    int32       `json:"stepnr"`
	Type      int32       `json:"type"`
	Drvpath   pgtype.Text `json:"drvpath"`
	Status    pgtype.Int4 `json:"status"`
	Machine   string      `json:"machine"`
	Starttime pgtype.Int4 `json:"starttime"`
	Stoptime  pgtype.Int4 `json:"stoptime"`
}

func (q *Queries) CreateBuildStep(ctx context.Context, arg CreateBuildStepParams) error {
	_, err := q.db.Exec(ctx, createBuildStep,
		arg.Build,
		arg.Stepnr,
		arg.Type,
		arg.Drvpath,
		arg.Status,
		arg.Machine,
		arg.Starttime,
		arg.Stoptime,
	)
	return err
}

const createBuildStepOutput = `-- name: CreateBuildStepOutput :exec
INSERT INTO buildstepoutputs (build, stepnr, name, path)
VALUES ($1, $2, $3, $4)
`

type CreateBuildStepOutputParams struct {
	Build  int32       `json:"build"`
	Stepnr int32       `json:"stepnr"`
	Name   string      `json:"name"`
	Path   pgtype.Text `json:"path"`
}

func (q *Queries) CreateBuildStepOutput(ctx context.Context, arg CreateBuildStepOutputParams) error {
	_, err := q.db.Exec(ctx, createBuildStepOutput,
		arg.Build,
		arg.Stepnr,
		arg.Name,
		arg.Path,
	)
	return err
}

const createJobset = `-- name: CreateJobset :one
INSERT INTO jobsets (name, project, description, nixexprinput, nixexprpath, enabled, emailoverride)
VALUES ($1, $2, $3, $4, $5, 1, '')
RETURNING name, id, project, description, nixexprinput, nixexprpath, errormsg, errortime, lastcheckedtime, triggertime, enabled, enableemail, hidden, emailoverride, keepnr, checkinterval, schedulingshares, fetcherrormsg, forceeval, starttime, type, flake, enable_dynamic_run_command
`

type CreateJobsetParams struct {
	Name         string      `json:"name"`
	Project      string      `json:"project"`
	Description  pgtype.Text `json:"description"`
	Nixexprinput pgtype.Text `json:"nixexprinput"`
	Nixexprpath  pgtype.Text `json:"nixexprpath"`
}

func (q *Queries) CreateJobset(ctx context.Context, arg CreateJobsetParams) (Jobset, error) {
	row := q.db.QueryRow(ctx, createJobset,
		arg.Name,
		arg.Project,
		arg.Description,
		arg.Nixexprinput,
		arg.Nixexprpath,
	)
	var i Jobset
	err := row.Scan(
		&i.Name,
		&i.ID,
		&i.Project,
		&i.Description,
		&i.Nixexprinput,
		&i.Nixexprpath,
		&i.Errormsg,
		&i.Errortime,
		&i.Lastcheckedtime,
		&i.Triggertime,
		&i.Enabled,
		&i.Enableemail,
		&i.Hidden,
		&i.Emailoverride,
		&i.Keepnr,
		&i.Checkinterval,
		&i.Schedulingshares,
		&i.Fetcherrormsg,
		&i.Forceeval,
		&i.Starttime,
		&i.Type,
		&i.Flake,
		&i.EnableDynamicRunCommand,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, displayname, description, owner, enabled)
VALUES ($1, $2, $3, $4, 1)
RETURNING name, displayname, description, enabled, hidden, owner, homepage, declfile, decltype, declvalue, enable_dynamic_run_command
`

type CreateProjectParams struct {
	Name        string      `json:"name"`
	Displayname string      `json:"displayname"`
	Description pgtype.Text `json:"description"`
	Owner       string      `json:"owner"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Displayname,
		arg.Description,
		arg.Owner,
	)
	var i Project
	err := row.Scan(
		&i.Name,
		&i.Displayname,
		&i.Description,
		&i.Enabled,
		&i.Hidden,
		&i.Owner,
		&i.Homepage,
		&i.Declfile,
		&i.Decltype,
		&i.Declvalue,
		&i.EnableDynamicRunCommand,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, fullname, emailaddress, password, type)
VALUES ($1, $2, $3, $4, 'hydra')
RETURNING username, fullname, emailaddress, password, emailonerror, type, publicdashboard
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Fullname     pgtype.Text `json:"fullname"`
	Emailaddress string      `json:"emailaddress"`
	Password     string      `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Fullname,
		arg.Emailaddress,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Fullname,
		&i.Emailaddress,
		&i.Password,
		&i.Emailonerror,
		&i.Type,
		&i.Publicdashboard,
	)
	return i, err
}

const deleteBuildStepOutputs = `-- name: DeleteBuildStepOutputs :execrows
DELETE from buildstepoutputs WHERE path = ANY($1::text[])
`

func (q *Queries) DeleteBuildStepOutputs(ctx context.Context, paths []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBuildStepOutputs, paths)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findBuildStepOutputs = `-- name: FindBuildStepOutputs :many
SELECT path FROM buildstepoutputs WHERE path = ANY($1::text[]) ORDER BY path
`

func (q *Queries) FindBuildStepOutputs(ctx context.Context, paths []string) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, findBuildStepOutputs, paths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var path pgtype.Text
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTables = `-- name: ListTables :many
SELECT
    table_name
FROM information_schema.tables
WHERE
    table_schema = 'public'
ORDER BY
    table_name
`

func (q *Queries) ListTables(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var table_name interface{}
		if err := rows.Scan(&table_name); err != nil {
			return nil, err
		}
		items = append(items, table_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
