// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNarInfoReferences = `-- name: InsertNarInfoReferences :exec
insert into nar_info_reference (hash, refers_to, created_at)
values ($1, $2, timezone('UTC', now()))
`

type InsertNarInfoReferencesParams struct {
	Hash     string `json:"hash"`
	RefersTo string `json:"refers_to"`
}

func (q *Queries) InsertNarInfoReferences(ctx context.Context, arg InsertNarInfoReferencesParams) error {
	_, err := q.db.Exec(ctx, insertNarInfoReferences, arg.Hash, arg.RefersTo)
	return err
}

const insertNarInfoSignatures = `-- name: InsertNarInfoSignatures :exec
insert into nar_info_signature (hash, signature, created_at)
values ($1, $2, timezone('UTC', now()))
`

type InsertNarInfoSignaturesParams struct {
	Hash      string `json:"hash"`
	Signature string `json:"signature"`
}

func (q *Queries) InsertNarInfoSignatures(ctx context.Context, arg InsertNarInfoSignaturesParams) error {
	_, err := q.db.Exec(ctx, insertNarInfoSignatures, arg.Hash, arg.Signature)
	return err
}

const narExists = `-- name: NarExists :one
select bucket, path, size
from nar_file
where hash = $1
`

type NarExistsRow struct {
	Bucket string      `json:"bucket"`
	Path   string      `json:"path"`
	Size   pgtype.Int8 `json:"size"`
}

func (q *Queries) NarExists(ctx context.Context, hash string) (NarExistsRow, error) {
	row := q.db.QueryRow(ctx, narExists, hash)
	var i NarExistsRow
	err := row.Scan(&i.Bucket, &i.Path, &i.Size)
	return i, err
}

const narInfoExists = `-- name: NarInfoExists :one
select bucket, path, size
from nar_info
where hash = $1
`

type NarInfoExistsRow struct {
	Bucket string `json:"bucket"`
	Path   string `json:"path"`
	Size   int32  `json:"size"`
}

func (q *Queries) NarInfoExists(ctx context.Context, hash string) (NarInfoExistsRow, error) {
	row := q.db.QueryRow(ctx, narInfoExists, hash)
	var i NarInfoExistsRow
	err := row.Scan(&i.Bucket, &i.Path, &i.Size)
	return i, err
}

const putNar = `-- name: PutNar :exec
insert into nar_file (hash, bucket, path, size, created_at)
values ($1, $2, $3, $4, timezone('UTC', now()))
on conflict
do nothing
`

type PutNarParams struct {
	Hash   string      `json:"hash"`
	Bucket string      `json:"bucket"`
	Path   string      `json:"path"`
	Size   pgtype.Int8 `json:"size"`
}

func (q *Queries) PutNar(ctx context.Context, arg PutNarParams) error {
	_, err := q.db.Exec(ctx, putNar,
		arg.Hash,
		arg.Bucket,
		arg.Path,
		arg.Size,
	)
	return err
}

const putNarInfo = `-- name: PutNarInfo :one
insert
into nar_info (hash, store_path, compression, file_hash, file_size, nar_hash, nar_size, deriver, bucket, path, size, created_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, timezone('UTC', now()))
    on conflict (hash)
do
update set hash = EXCLUDED.hash
    returning hash, (xmax = 0) as inserted
`

type PutNarInfoParams struct {
	Hash        string          `json:"hash"`
	StorePath   string          `json:"store_path"`
	Compression CompressionType `json:"compression"`
	FileHash    string          `json:"file_hash"`
	FileSize    pgtype.Int8     `json:"file_size"`
	NarHash     string          `json:"nar_hash"`
	NarSize     pgtype.Int8     `json:"nar_size"`
	Deriver     string          `json:"deriver"`
	Bucket      string          `json:"bucket"`
	Path        string          `json:"path"`
	Size        int32           `json:"size"`
}

type PutNarInfoRow struct {
	Hash     string `json:"hash"`
	Inserted bool   `json:"inserted"`
}

func (q *Queries) PutNarInfo(ctx context.Context, arg PutNarInfoParams) (PutNarInfoRow, error) {
	row := q.db.QueryRow(ctx, putNarInfo,
		arg.Hash,
		arg.StorePath,
		arg.Compression,
		arg.FileHash,
		arg.FileSize,
		arg.NarHash,
		arg.NarSize,
		arg.Deriver,
		arg.Bucket,
		arg.Path,
		arg.Size,
	)
	var i PutNarInfoRow
	err := row.Scan(&i.Hash, &i.Inserted)
	return i, err
}
