// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package hydra

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Aggregateconstituent struct {
	Aggregate   int32 `json:"aggregate"`
	Constituent int32 `json:"constituent"`
}

type Build struct {
	ID                       int32       `json:"id"`
	Finished                 int32       `json:"finished"`
	Timestamp                int32       `json:"timestamp"`
	JobsetID                 int32       `json:"jobset_id"`
	Job                      string      `json:"job"`
	Nixname                  pgtype.Text `json:"nixname"`
	Description              pgtype.Text `json:"description"`
	Drvpath                  string      `json:"drvpath"`
	System                   string      `json:"system"`
	License                  pgtype.Text `json:"license"`
	Homepage                 pgtype.Text `json:"homepage"`
	Maintainers              pgtype.Text `json:"maintainers"`
	Maxsilent                pgtype.Int4 `json:"maxsilent"`
	Timeout                  pgtype.Int4 `json:"timeout"`
	Ischannel                int32       `json:"ischannel"`
	Iscurrent                pgtype.Int4 `json:"iscurrent"`
	Priority                 int32       `json:"priority"`
	Globalpriority           int32       `json:"globalpriority"`
	Starttime                pgtype.Int4 `json:"starttime"`
	Stoptime                 pgtype.Int4 `json:"stoptime"`
	Iscachedbuild            pgtype.Int4 `json:"iscachedbuild"`
	Buildstatus              pgtype.Int4 `json:"buildstatus"`
	Size                     pgtype.Int8 `json:"size"`
	Closuresize              pgtype.Int8 `json:"closuresize"`
	Releasename              pgtype.Text `json:"releasename"`
	Keep                     int32       `json:"keep"`
	Notificationpendingsince pgtype.Int4 `json:"notificationpendingsince"`
}

type Buildinput struct {
	ID               int32       `json:"id"`
	Build            pgtype.Int4 `json:"build"`
	Name             string      `json:"name"`
	Type             string      `json:"type"`
	Uri              pgtype.Text `json:"uri"`
	Revision         pgtype.Text `json:"revision"`
	Value            pgtype.Text `json:"value"`
	Emailresponsible int32       `json:"emailresponsible"`
	Dependency       pgtype.Int4 `json:"dependency"`
	Path             pgtype.Text `json:"path"`
	Sha256hash       pgtype.Text `json:"sha256hash"`
}

type Buildmetric struct {
	Build     int32       `json:"build"`
	Name      string      `json:"name"`
	Unit      pgtype.Text `json:"unit"`
	Value     float64     `json:"value"`
	Project   string      `json:"project"`
	Jobset    string      `json:"jobset"`
	Job       string      `json:"job"`
	Timestamp int32       `json:"timestamp"`
}

type Buildoutput struct {
	Build int32       `json:"build"`
	Name  string      `json:"name"`
	Path  pgtype.Text `json:"path"`
}

type Buildproduct struct {
	Build       int32       `json:"build"`
	Productnr   int32       `json:"productnr"`
	Type        string      `json:"type"`
	Subtype     string      `json:"subtype"`
	Filesize    pgtype.Int8 `json:"filesize"`
	Sha256hash  pgtype.Text `json:"sha256hash"`
	Path        pgtype.Text `json:"path"`
	Name        string      `json:"name"`
	Defaultpath pgtype.Text `json:"defaultpath"`
}

type Buildstep struct {
	Build              int32       `json:"build"`
	Stepnr             int32       `json:"stepnr"`
	Type               int32       `json:"type"`
	Drvpath            pgtype.Text `json:"drvpath"`
	Busy               int32       `json:"busy"`
	Status             pgtype.Int4 `json:"status"`
	Errormsg           pgtype.Text `json:"errormsg"`
	Starttime          pgtype.Int4 `json:"starttime"`
	Stoptime           pgtype.Int4 `json:"stoptime"`
	Machine            string      `json:"machine"`
	System             pgtype.Text `json:"system"`
	Propagatedfrom     pgtype.Int4 `json:"propagatedfrom"`
	Overhead           pgtype.Int4 `json:"overhead"`
	Timesbuilt         pgtype.Int4 `json:"timesbuilt"`
	Isnondeterministic pgtype.Bool `json:"isnondeterministic"`
}

type Buildstepoutput struct {
	Build  int32       `json:"build"`
	Stepnr int32       `json:"stepnr"`
	Name   string      `json:"name"`
	Path   pgtype.Text `json:"path"`
}

type Cachedbazaarinput struct {
	Uri        string `json:"uri"`
	Revision   int32  `json:"revision"`
	Sha256hash string `json:"sha256hash"`
	Storepath  string `json:"storepath"`
}

type Cachedcvsinput struct {
	Uri        string `json:"uri"`
	Module     string `json:"module"`
	Timestamp  int32  `json:"timestamp"`
	Lastseen   int32  `json:"lastseen"`
	Sha256hash string `json:"sha256hash"`
	Storepath  string `json:"storepath"`
}

type Cacheddarcsinput struct {
	Uri        string `json:"uri"`
	Revision   string `json:"revision"`
	Sha256hash string `json:"sha256hash"`
	Storepath  string `json:"storepath"`
	Revcount   int32  `json:"revcount"`
}

type Cachedgitinput struct {
	Uri         string `json:"uri"`
	Branch      string `json:"branch"`
	Revision    string `json:"revision"`
	Isdeepclone bool   `json:"isdeepclone"`
	Sha256hash  string `json:"sha256hash"`
	Storepath   string `json:"storepath"`
}

type Cachedhginput struct {
	Uri        string `json:"uri"`
	Branch     string `json:"branch"`
	Revision   string `json:"revision"`
	Sha256hash string `json:"sha256hash"`
	Storepath  string `json:"storepath"`
}

type Cachedpathinput struct {
	Srcpath    string `json:"srcpath"`
	Timestamp  int32  `json:"timestamp"`
	Lastseen   int32  `json:"lastseen"`
	Sha256hash string `json:"sha256hash"`
	Storepath  string `json:"storepath"`
}

type Cachedsubversioninput struct {
	Uri        string `json:"uri"`
	Revision   int32  `json:"revision"`
	Sha256hash string `json:"sha256hash"`
	Storepath  string `json:"storepath"`
}

type Evaluationerror struct {
	ID        int32       `json:"id"`
	Errormsg  pgtype.Text `json:"errormsg"`
	Errortime pgtype.Int4 `json:"errortime"`
}

type Failedpath struct {
	Path string `json:"path"`
}

type Jobset struct {
	Name                    string      `json:"name"`
	ID                      int32       `json:"id"`
	Project                 string      `json:"project"`
	Description             pgtype.Text `json:"description"`
	Nixexprinput            pgtype.Text `json:"nixexprinput"`
	Nixexprpath             pgtype.Text `json:"nixexprpath"`
	Errormsg                pgtype.Text `json:"errormsg"`
	Errortime               pgtype.Int4 `json:"errortime"`
	Lastcheckedtime         pgtype.Int4 `json:"lastcheckedtime"`
	Triggertime             pgtype.Int4 `json:"triggertime"`
	Enabled                 int32       `json:"enabled"`
	Enableemail             int32       `json:"enableemail"`
	Hidden                  int32       `json:"hidden"`
	Emailoverride           string      `json:"emailoverride"`
	Keepnr                  int32       `json:"keepnr"`
	Checkinterval           int32       `json:"checkinterval"`
	Schedulingshares        int32       `json:"schedulingshares"`
	Fetcherrormsg           pgtype.Text `json:"fetcherrormsg"`
	Forceeval               pgtype.Bool `json:"forceeval"`
	Starttime               pgtype.Int4 `json:"starttime"`
	Type                    int32       `json:"type"`
	Flake                   pgtype.Text `json:"flake"`
	EnableDynamicRunCommand bool        `json:"enable_dynamic_run_command"`
}

type Jobseteval struct {
	ID                int32       `json:"id"`
	JobsetID          int32       `json:"jobset_id"`
	EvaluationerrorID pgtype.Int4 `json:"evaluationerror_id"`
	Timestamp         int32       `json:"timestamp"`
	Checkouttime      int32       `json:"checkouttime"`
	Evaltime          int32       `json:"evaltime"`
	Hasnewbuilds      int32       `json:"hasnewbuilds"`
	Hash              string      `json:"hash"`
	Nrbuilds          pgtype.Int4 `json:"nrbuilds"`
	Nrsucceeded       pgtype.Int4 `json:"nrsucceeded"`
	Flake             pgtype.Text `json:"flake"`
	Nixexprinput      pgtype.Text `json:"nixexprinput"`
	Nixexprpath       pgtype.Text `json:"nixexprpath"`
}

type Jobsetevalinput struct {
	Eval       int32       `json:"eval"`
	Name       string      `json:"name"`
	Altnr      int32       `json:"altnr"`
	Type       string      `json:"type"`
	Uri        pgtype.Text `json:"uri"`
	Revision   pgtype.Text `json:"revision"`
	Value      pgtype.Text `json:"value"`
	Dependency pgtype.Int4 `json:"dependency"`
	Path       pgtype.Text `json:"path"`
	Sha256hash pgtype.Text `json:"sha256hash"`
}

type Jobsetevalmember struct {
	Eval  int32 `json:"eval"`
	Build int32 `json:"build"`
	Isnew int32 `json:"isnew"`
}

type Jobsetinput struct {
	Project          string `json:"project"`
	Jobset           string `json:"jobset"`
	Name             string `json:"name"`
	Type             string `json:"type"`
	Emailresponsible int32  `json:"emailresponsible"`
}

type Jobsetinputalt struct {
	Project  string      `json:"project"`
	Jobset   string      `json:"jobset"`
	Input    string      `json:"input"`
	Altnr    int32       `json:"altnr"`
	Value    pgtype.Text `json:"value"`
	Revision pgtype.Text `json:"revision"`
}

type Jobsetrename struct {
	Project string `json:"project"`
	From    string `json:"from_"`
	To      string `json:"to_"`
}

type Newsitem struct {
	ID         int32  `json:"id"`
	Contents   string `json:"contents"`
	Createtime int32  `json:"createtime"`
	Author     string `json:"author"`
}

type Nrbuild struct {
	What  string `json:"what"`
	Count int32  `json:"count"`
}

type Project struct {
	Name                    string      `json:"name"`
	Displayname             string      `json:"displayname"`
	Description             pgtype.Text `json:"description"`
	Enabled                 int32       `json:"enabled"`
	Hidden                  int32       `json:"hidden"`
	Owner                   string      `json:"owner"`
	Homepage                pgtype.Text `json:"homepage"`
	Declfile                pgtype.Text `json:"declfile"`
	Decltype                pgtype.Text `json:"decltype"`
	Declvalue               pgtype.Text `json:"declvalue"`
	EnableDynamicRunCommand bool        `json:"enable_dynamic_run_command"`
}

type Projectmember struct {
	Project  string `json:"project"`
	Username string `json:"username"`
}

type Runcommandlog struct {
	ID          int32       `json:"id"`
	Uuid        pgtype.UUID `json:"uuid"`
	JobMatcher  string      `json:"job_matcher"`
	BuildID     int32       `json:"build_id"`
	Command     string      `json:"command"`
	StartTime   pgtype.Int4 `json:"start_time"`
	EndTime     pgtype.Int4 `json:"end_time"`
	ErrorNumber pgtype.Int4 `json:"error_number"`
	ExitCode    pgtype.Int4 `json:"exit_code"`
	Signal      pgtype.Int4 `json:"signal"`
	CoreDumped  pgtype.Bool `json:"core_dumped"`
}

type Schemaversion struct {
	Version int32 `json:"version"`
}

type Starredjob struct {
	Username string `json:"username"`
	Project  string `json:"project"`
	Jobset   string `json:"jobset"`
	Job      string `json:"job"`
}

type Systemstatus struct {
	What   string `json:"what"`
	Status []byte `json:"status"`
}

type Taskretry struct {
	ID         int32  `json:"id"`
	Channel    string `json:"channel"`
	Pluginname string `json:"pluginname"`
	Payload    string `json:"payload"`
	Attempts   int32  `json:"attempts"`
	RetryAt    int32  `json:"retry_at"`
}

type Urirevmapper struct {
	Baseuri string `json:"baseuri"`
	Uri     string `json:"uri"`
}

type User struct {
	Username        string      `json:"username"`
	Fullname        pgtype.Text `json:"fullname"`
	Emailaddress    string      `json:"emailaddress"`
	Password        string      `json:"password"`
	Emailonerror    int32       `json:"emailonerror"`
	Type            string      `json:"type"`
	Publicdashboard bool        `json:"publicdashboard"`
}

type Userrole struct {
	Username string `json:"username"`
	Role     string `json:"role"`
}
