// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package hydra

import (
	"context"
)

const listTables = `-- name: ListTables :many
SELECT
    table_name
FROM information_schema.tables
WHERE
    table_schema = 'public'
ORDER BY
    table_name
`

func (q *Queries) ListTables(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var table_name interface{}
		if err := rows.Scan(&table_name); err != nil {
			return nil, err
		}
		items = append(items, table_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
